#
# PX4 docs build environment
#

FROM ubuntu:jammy
LABEL maintainer="Daniel Agar <daniel@agar.ca>"

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install \
		build-essential \
		ca-certificates \
		git \
		gosu \
		libfontconfig \
		ruby-dev \
		zlib1g-dev \
		curl \
		gnupg \
		gnupg2 \
		gnupg1 \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install Node.js 18 and npm
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
	&& apt-get install -y nodejs

# Install yarn
RUN npm install --global yarn

# Install html-proofer
RUN gem install html-proofer

# create user with id 1001 (jenkins docker workflow default)
RUN useradd --shell /bin/bash -u 1001 -c "" -m user && usermod -a -G dialout user

USER user
ENV NPM_CONFIG_PREFIX=/home/user/.npm-global
ENV PATH=$PATH:/home/user/.npm-global/bin

ENV TERM=xterm
ENV TZ=UTC

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
