#
# PX4 ROS2 development environment
# Based from container under https://github.com/osrf/docker_images/tree/master/ros2/source/devel
#

FROM px4io/px4-dev-ros-melodic:2020-05-28
LABEL maintainer="Nuno Marques <n.marques21@hotmail.com>"

# setup environment
ENV ROS1_DISTRO melodic
ENV ROS2_DISTRO dashing

# setup ros2 keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup sources.list
RUN echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros2-latest.list \
	&& apt-get update

# install ros2 desktop
RUN apt-get install -y --quiet \
		python3-colcon-common-extensions \
		python3-vcstool \
		ros-$ROS2_DISTRO-desktop \
		ros-$ROS2_DISTRO-launch-testing-ament-cmake \
		ros-$ROS2_DISTRO-ros2bag \
		ros-$ROS2_DISTRO-rosidl-generator-dds-idl \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install Python 3 packages needed for testing
RUN pip3 install --upgrade \
		argcomplete \
		colcon-common-extensions \
		colcon-mixin \
		flake8 \
		flake8-blind-except \
		flake8-builtins \
		flake8-class-newline \
		flake8-comprehensions \
		flake8-deprecated \
		flake8-docstrings \
		flake8-import-order \
		flake8-quotes \
		pytest-repeat \
		pytest-rerunfailures

RUN rosdep update

# setup colcon mixin and metadata
RUN colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml \
	&& colcon mixin update \
	&& colcon metadata add default https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml \
	&& colcon metadata update
