#
# PX4 NuttX development environment in Ubuntu 18.04 Bionic
#

FROM px4io/px4-dev-base-bionic:2020-11-02
LABEL maintainer="Daniel Agar <daniel@agar.ca>"

RUN cd /tmp \
	&& wget https://raw.githubusercontent.com/PX4/Firmware/master/Tools/setup/ubuntu.sh \
	&& wget https://raw.githubusercontent.com/PX4/Firmware/master/Tools/setup/requirements.txt \
	&& bash ubuntu.sh --no-sim-tools \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
	&& rm -rf /opt/gcc/share/doc

ENV PATH="$PATH:/opt/gcc/bin"

# nuttx tools
RUN git clone --depth 1 https://bitbucket.org/nuttx/tools.git /tmp/tools \
	&& cd /tmp/tools/kconfig-frontends \
	&& autoreconf -f -i \
	&& ./configure --enable-mconf --disable-nconf --disable-gconf --disable-qconf -prefix=/usr && make -j$(nproc) && make install \
	&& rm -rf /tmp/*

# bloaty - https://github.com/google/bloaty
RUN git clone --recursive https://github.com/google/bloaty.git /tmp/bloaty \
	&& cd /tmp/bloaty && cmake -GNinja . && ninja -j $(nproc) bloaty && cp bloaty /usr/local/bin/ \
	&& rm -rf /tmp/*

# cleanup
RUN rm -rf \
	/var/lib/apt/lists/* \
	/tmp/* /var/tmp/* \
	/root/.cache \
	/root/.gradle \
	/root/.local

