#
# PX4 development environment based on Arch Linux
#

FROM archlinux:base
LABEL maintainer="Julien Lecoeur <julien.lecoeur@gmail.com>"

RUN pacman -Syu --noconfirm

RUN pacman -Sy --noconfirm \
		arm-none-eabi-gcc \
		arm-none-eabi-newlib \
		base-devel \
		bc \
		ccache \
		cmake \
		git \
		gnutls \
		jdk11-openjdk \
		make \
		nettle \
		ninja \
		python-pip \
		python-setuptools \
		tar \
		unzip \
		valgrind \
		vim \
		wget \
		zip

# Create a virtual environment for Python packages
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install wheel and setuptools in the virtual environment
RUN pip3 install wheel setuptools

# Python 3 dependencies installed by pip inside the virtual environment
RUN pip3 install argparse argcomplete coverage cerberus empy==3.3.4 jinja2 \
		kconfiglib matplotlib numpy packaging pkgconfig pyros-genmsg pyulog \
		pyyaml requests serial six toml psutil pyulog wheel jsonschema

# Install genromfs
RUN wget https://sourceforge.net/projects/romfs/files/genromfs/0.5.2/genromfs-0.5.2.tar.gz \
	&& tar zxvf genromfs-0.5.2.tar.gz \
	&& cd genromfs-0.5.2 && make -j$(nproc) && make install && cd .. \
	&& rm genromfs-0.5.2.tar.gz genromfs-0.5.2 -r

# Install gosu
RUN curl -sSL https://github.com/tianon/gosu/releases/download/1.8/gosu-amd64 > /usr/sbin/gosu \
	&& chmod +x /usr/sbin/gosu

# Add group dialout
RUN groupadd dialout

# manual ccache setup
RUN ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-gcc \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-g++

ENV CCACHE_MAXSIZE=1G
ENV PATH "/usr/lib/ccache/bin:$PATH"
ENV TERM=xterm

# SITL UDP PORTS
EXPOSE 14556/udp
EXPOSE 14557/udp

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
