#
# PX4 development environment based on Arch Linux
#

FROM archlinux:base
LABEL maintainer="Julien Lecoeur <julien.lecoeur@gmail.com>"

RUN pacman -Syu --noconfirm

RUN pacman -Sy --noconfirm \
		arm-none-eabi-gcc \
		arm-none-eabi-newlib \
		base-devel \
		bc \
		ccache \
		cmake \
		git \
		gnutls \
		jdk11-openjdk \
		make \
		nettle \
		ninja \
		python-pip \
		python-setuptools \
		tar \
		unzip \
		valgrind \
		vim \
		wget \
		zip

# Python 3 dependencies installed by pip
RUN pip3 install argparse argcomplete coverage cerberus empy jinja2 kconfiglib \
		matplotlib==3.0.* numpy packaging pkgconfig pyros-genmsg pyulog \
		pyyaml requests serial six toml psutil pyulog wheel jsonschema

# Install genromfs
RUN wget https://sourceforge.net/projects/romfs/files/genromfs/0.5.2/genromfs-0.5.2.tar.gz \
	&& tar zxvf genromfs-0.5.2.tar.gz \
	&& cd genromfs-0.5.2 && make -j$(nproc) && make install && cd .. \
	&& rm genromfs-0.5.2.tar.gz genromfs-0.5.2 -r

# Install gosu
RUN curl -sSL https://github.com/tianon/gosu/releases/download/1.8/gosu-amd64 > /usr/sbin/gosu \
	&& chmod +x /usr/sbin/gosu

# Gradle (Required to build Fast-RTPS-Gen)
RUN wget -q "https://services.gradle.org/distributions/gradle-6.1-rc-3-bin.zip" -O /tmp/gradle-6.1-rc-3-bin.zip \
	&& mkdir /opt/gradle \
	&& cd /tmp \
	&& unzip -d /opt/gradle gradle-6.1-rc-3-bin.zip \
	&& rm -rf /tmp/*

ENV PATH "/opt/gradle/gradle-6.1-rc-3/bin:$PATH"

# Intall foonathan_memory from source as it is required to Fast-RTPS >= 1.9
RUN git clone https://github.com/eProsima/foonathan_memory_vendor.git /tmp/foonathan_memory \
	&& cd /tmp/foonathan_memory \
	&& mkdir build && cd build \
	&& cmake .. \
	&& cmake --build . --target install -- -j $(nproc) \
	&& rm -rf /tmp/*

# Fast-DDS 2.0.0
RUN git clone --recursive https://github.com/eProsima/Fast-DDS.git -b v2.0.0 /tmp/FastRTPS-2.0.0 \
	&& cd /tmp/FastRTPS-2.0.0 \
	&& mkdir build && cd build \
	&& cmake -DTHIRDPARTY=ON -DSECURITY=ON .. \
	&& cmake --build . --target install -- -j $(nproc) \
	&& rm -rf /tmp/*

# Fast-RTPS-Gen 1.0.4
RUN git clone --recursive https://github.com/eProsima/Fast-DDS-Gen.git -b v1.0.4 /tmp/Fast-RTPS-Gen-1.0.4 \
	&& cd /tmp/Fast-RTPS-Gen-1.0.4 \
	&& gradle assemble \
	&& gradle install \
	&& rm -rf /tmp/*

# Add group dialout
RUN groupadd dialout

# manual ccache setup
RUN ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-gcc \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-g++

ENV CCACHE_MAXSIZE=1G
ENV FASTRTPSGEN_DIR="/usr/local/bin/"
ENV PATH "/usr/lib/ccache/bin:$PATH"
ENV TERM=xterm

# SITL UDP PORTS
EXPOSE 14556/udp
EXPOSE 14557/udp

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
