#
# PX4 build for RPi and Parrot Bebop
#
# This contains the steps to build for the POSIX Linux running on
# Raspberry Pi or Parrot Bebop
#

FROM px4io/px4-dev-base-bionic:2021-09-08
LABEL maintainer="Michael Schaeuble"

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install \
		sudo \
	&& mkdir -p /home/user \
	&& git clone https://github.com/pixhawk/rpi_toolchain.git /home/user/rpi_toolchain \
	&& cd /home/user/rpi_toolchain \
	&& ./install_cross.sh /home/user/rpi_toolchain_install \
	&& rm -rf /home/user/rpi_toolchain \
	# cleanup
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# TODO: Remove this line after the toolchain update PR gets merged
ENV RPI_TOOLCHAIN_DIR=/home/user/rpi_toolchain_install

ENV PATH="$PATH:/home/user/rpi_toolchain_install/gcc-linaro-arm-linux-gnueabihf-raspbian/bin"

# manual ccache setup
RUN	ln -s /usr/bin/ccache /usr/lib/ccache/arm-linux-gnueabihf-gcc \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/arm-linux-gnueabihf-g++
