#
# PX4 clang development environment
#  px4-dev-base + latest clang
#

FROM px4io/px4-dev-base-focal:2022-08-12
LABEL maintainer="Daniel Agar <daniel@agar.ca>"

RUN wget --quiet http://apt.llvm.org/llvm-snapshot.gpg.key -O - | apt-key add - \
	&& sh -c 'echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main" >> /etc/apt/sources.list' \
	&& sh -c 'echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" >> /etc/apt/sources.list' \
	&& apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install \
		clang-14 \
		clang-format-14 \
		clang-tidy-14 \
		lldb-14 \
		llvm-14 \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# clang-tidy version setup
RUN	update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 1 \
	&& update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 1 \
	&& update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-14 1 \
	&& update-alternatives --install /usr/bin/run-clang-tidy.py run-clang-tidy.py /usr/bin/run-clang-tidy-14.py 1 \
	&& update-alternatives --install /usr/bin/scan-build scan-build /usr/bin/scan-build-14 1

# manual ccache setup
RUN	ln -s /usr/bin/ccache /usr/lib/ccache/clang \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/clang++

# Link legacy Python to Python 3
RUN ln -s /usr/bin/python3 /usr/bin/python

ENV CCACHE_CPP2=1
