#
# PX4 Gazebo (classic) 9 / Igntion Edifice development environment in Ubuntu 18.04 Bionic
#

FROM px4io/px4-dev-base-bionic:2024-05-17
LABEL maintainer="Daniel Agar <daniel@agar.ca>"

RUN wget --quiet http://packages.osrfoundation.org/gazebo.key -O - | apt-key add - \
	&& sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -sc` main" > /etc/apt/sources.list.d/gazebo-stable.list' \
	&& apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install \
		ant \
		bc \
		gazebo9 \
		gstreamer1.0-plugins-bad \
		gstreamer1.0-plugins-base \
		gstreamer1.0-plugins-good \
		gstreamer1.0-plugins-ugly \
		libeigen3-dev \
		libgazebo9-dev \
		libgstreamer-plugins-base1.0-dev \
		libimage-exiftool-perl \
		libopencv-dev \
		libxml2-utils \
		protobuf-compiler \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install dependencies for building Ignition Edifice from source
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
		build-essential \
		libbz2-dev \
		libcurl4-openssl-dev \
		libdw-dev \
		libfreeimage-dev \
		libgflags-dev \
		libglew-dev \
		libglm-dev \
		libgts-dev \
		libjansson-dev \
		libprotobuf-dev \
		libogre-1.9-dev \
		libogre-2.1-dev \
		libsqlite3-dev \
		libswscale-dev \
		libtinyxml2-dev \
		libwebsockets-dev \
		python3 \
		libignition-gui5-dev \
		qtbase5-dev \
		qtdeclarative5-dev \
		qtquickcontrols2-5-dev \
		ruby-ronn \
		uuid-dev \
	&& apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Clone, build and install Ignition Edifice and libraries
RUN for repo in \
		ign-cmake:ignition-cmake2_2.7.0 \
		ign-common:ignition-common4_4.0.0 \
		ign-math:ignition-math6_6.8.0 \
		ign-msgs:ignition-msgs7_7.0.0 \
		ign-plugin:ignition-plugin_1.2.0 \
		ign-launch:ignition-launch4_4.0.0 \
		ign-transport:ignition-transport10_10.0.0 \
		ign-fuel-tools:ignition-fuel-tools6_6.0.0 \
		ign-gui:ignition-gui5_5.0.0 \
		ign-rendering:ignition-rendering5_5.0.0 \
		ign-physics:ignition-physics4_4.0.0 \
		ign-sensors:ignition-sensors5_5.0.0 \
		ign-gazebo:ignition-gazebo5_5.0.0 \
		ign-tools:ignition-tools_1.1.0; \
	do \
		cd /root; \
		repo_name=$(echo $repo | cut -d: -f1); \
		repo_branch=$(echo $repo | cut -d: -f2); \
		git clone https://github.com/ignitionrobotics/$repo_name.git -b $repo_branch /root/$repo_name \
		&& cd /root/$repo_name && mkdir build && cd build && cmake .. && make && make install \
		&& rm -rf /root/$repo_name; \
	done

# Some QT-Apps/Gazebo don't not show controls without this
ENV QT_X11_NO_MITSHM 1

# Use UTF8 encoding in java tools (needed to compile jMAVSim)
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

# Install JSBSim
RUN wget https://github.com/JSBSim-Team/jsbsim/releases/download/v1.1.1a/JSBSim-devel_1.1.1-134.bionic.amd64.deb
RUN dpkg -i JSBSim-devel_1.1.1-134.bionic.amd64.deb
