#
# PX4 base development environment
#

FROM ubuntu:xenial
MAINTAINER Daniel Agar <daniel@agar.ca>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		astyle \
		bzip2 \
		ca-certificates \
		ccache \
		cmake \
		g++ \
		gcc \
		genromfs \
		git \
		gosu \
		lcov \
		make \
		ninja-build \
		patch \
		python-argparse \
		python-empy \
		python-serial \
		rsync \
		sudo \
		unzip \
		wget \
		xsltproc \
		zip \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/cc \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/c++ \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

ENV CCACHE_CPP2=1
ENV CCACHE_MAXSIZE=1G
ENV CCACHE_TEMPDIR=/tmp/.ccache
ENV DISPLAY :0
ENV PATH "/usr/lib/ccache:$PATH"
ENV TERM=xterm

# SITL UDP PORTS
EXPOSE 14556/udp
EXPOSE 14557/udp

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
