#
# PX4 gazebo development environment
#

FROM px4io/px4-dev-base
MAINTAINER Daniel Agar <daniel@agar.ca>

RUN wget --quiet http://packages.osrfoundation.org/gazebo.key -O - | apt-key add - \
	&& sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list' \
	&& apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		ant \
		gazebo7 \
		gstreamer1.0-plugins-base \
		libeigen3-dev \
		libgazebo7-dev \
		libopencv-dev \
		pkg-config \
		protobuf-compiler \
	# install MAVLink headers
	&& git clone https://github.com/mavlink/c_library_v2.git \
	&& mkdir -p /usr/local/mavlink/ && cp c_library_v2/. /usr/local/mavlink \
	# cleanup
	&& rm -rf c_library_v2 \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Some QT-Apps/Gazebo don't not show controls without this
ENV QT_X11_NO_MITSHM 1

# Gazebo 7 crashes on VM with OpenGL 3.3 support, so downgrade to OpenGL 2.1
# http://answers.gazebosim.org/question/13214/virtual-machine-not-launching-gazebo/
# https://www.mesa3d.org/vmware-guest.html
ENV SVGA_VGPU10 0

# Use UTF8 encoding in java tools (needed to compile jMAVSim)
ENV JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
