#
# PX4 clang development environment
#  px4-dev-base + latest clang
#

FROM px4io/px4-dev-base
MAINTAINER Daniel Agar <daniel@agar.ca>

RUN wget --quiet http://apt.llvm.org/llvm-snapshot.gpg.key -O - | apt-key add - \
	&& sh -c 'echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" >> /etc/apt/sources.list' \
	&& sh -c 'echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main" >> /etc/apt/sources.list' \
	&& apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		clang \
		clang-4.0 \
		clang-format-4.0 \
		clang-tidy-4.0 \
		llvm-4.0 \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	## clang-tidy
	&& update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 1 \
	&& update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-4.0 1 \
	&& update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-4.0 1 \
	&& update-alternatives --install /usr/bin/run-clang-tidy.py run-clang-tidy.py /usr/bin/run-clang-tidy-4.0.py 1 \
	# cleanup
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

