#
# PX4 ROS2 development environment
# Based from container under https://github.com/osrf/docker_images/tree/master/ros2/source
#

FROM px4io/px4-dev-ros-kinetic:2019-06-02
LABEL maintainer="Nuno Marques <n.marques21@hotmail.com>"

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS1_DISTRO kinetic
ENV ROS2_DISTRO ardent
ENV DEBIAN_FRONTEND noninteractive

# setup ros2 keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup sources.list
RUN echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros2-latest.list \
	&& apt-get update

# install ros2 desktop and ros1-bridge
RUN apt-get install -y --quiet \
		ros-$ROS2_DISTRO-desktop \
		ros-$ROS2_DISTRO-ros1-bridge \
		ros-$ROS2_DISTRO-rosidl-generator-dds-idl \
		dirmngr \
		gnupg2 \
		python3-dev \
		python3-colcon-common-extensions \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# install python packages needed for testing
RUN curl https://bootstrap.pypa.io/get-pip.py | python3 \
	&& python3 -m pip install --upgrade pip \
		setuptools \
		argcomplete \
		flake8 \
		flake8-blind-except \
		flake8-builtins \
		flake8-class-newline \
		flake8-comprehensions \
		flake8-deprecated \
		flake8-docstrings \
		flake8-import-order \
		flake8-quotes \
		pytest-repeat \
		pytest-rerunfailures

# Install python3-genmsg and python-gencpp or download and install from deb source (currently only available in Ubuntu 18.10 and above)
RUN apt-get install -y --quiet python3-genmsg \
	|| wget http://mirrors.kernel.org/ubuntu/pool/universe/r/ros-genmsg/python3-genmsg_0.5.11-2_all.deb -P /tmp/ \
		&& dpkg -i /tmp/python3-genmsg_0.5.11-2_all.deb \
		&& apt-get -y autoremove \
		&& apt-get clean autoclean \
		&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN apt-get install -y --quiet python3-gencpp \
	|| wget http://mirrors.kernel.org/ubuntu/pool/universe/r/ros-gencpp/python3-gencpp_0.6.0-4_all.deb -P /tmp/ \
		&& dpkg -i /tmp/python3-gencpp_0.6.0-4_all.deb \
		&& apt-get -y autoremove \
		&& apt-get clean autoclean \
		&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*
