#
# PX4 development environment based on Arch Linux
#

FROM pritunl/archlinux:2017-12-02
MAINTAINER Julien Lecoeur <julien.lecoeur@gmail.com>

RUN cat /etc/pacman.conf

# Enable multilib repository
RUN echo -e "[multilib] \nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

# Install required PX4 packages
RUN yes | pacman -Sy --noconfirm \
		base-devel \
		make \
		cmake \
		lib32-glibc \
		git-core \
		python-pip \
		zip \
		unzip \
		vim \
		wget \
		arm-none-eabi-gcc \
		arm-none-eabi-newlib
	
# Install genromfs
RUN wget https://sourceforge.net/projects/romfs/files/genromfs/0.5.2/genromfs-0.5.2.tar.gz \ 
	&& tar zxvf genromfs-0.5.2.tar.gz \
	&& cd genromfs-0.5.2 && make && make install && cd .. \
	&& rm genromfs-0.5.2.tar.gz genromfs-0.5.2 -r

# Install python dependencies
RUN pip install \
		serial \
		empy \
		numpy \
		toml \
		jinja2

# Install gosu
RUN curl -sSL https://github.com/tianon/gosu/releases/download/1.8/gosu-amd64 > /usr/sbin/gosu \
	&& chmod +x /usr/sbin/gosu 

# Install yaourt
RUN echo -e "[archlinuxfr] \nSigLevel = Never \nServer = http://repo.archlinux.fr/\$arch" >> /etc/pacman.conf \
	&& pacman -Sy --noconfirm yaourt

# Add group dialout
RUN groupadd dialout

ENV CCACHE_CPP2=1
ENV CCACHE_MAXSIZE=1G
ENV DISPLAY :0
ENV PATH "/usr/lib/ccache:$PATH"
ENV TERM=xterm

# SITL UDP PORTS
EXPOSE 14556/udp
EXPOSE 14557/udp

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
