#
# PX4 base development environment
#

FROM ubuntu:xenial
MAINTAINER Daniel Agar <daniel@agar.ca>

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install \
		bzip2 \
		ca-certificates \
		ccache \
		cmake \
		curl \
		g++ \
		gcc \
		git \
		gosu \
		lcov \
		make \
		ninja-build \
		openjdk-8-jdk-headless \
		patch \
		python-argparse \
		python-pip \
		python-serial \
		python-software-properties \
		rsync \
		software-properties-common \
		sudo \
		unzip \
		vim-common \
		wget \
		xsltproc \
		zip \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	# pip
	&& pip install --upgrade pip \
	&& pip install setuptools && pip install jinja2 empy numpy toml \
	# astyle v2.06
	&& wget https://downloads.sourceforge.net/project/astyle/astyle/astyle%202.06/astyle_2.06_linux.tar.gz -O /tmp/astyle.tar.gz \
	&& tar -xvf /tmp/astyle.tar.gz && cd astyle/src && make -f ../build/gcc/Makefile && cp bin/astyle /usr/local/bin && cd .. && rm -rf astyle \
	# bloaty - https://github.com/google/bloaty
	&& git clone https://github.com/google/bloaty.git /tmp/bloaty && cd /tmp/bloaty && cmake . && make && cp bloaty /usr/local/bin/ \
	# manual ccache setup
	&& ln -s /usr/bin/ccache /usr/lib/ccache/cc \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/c++ \
	# Add Fast-RTPS
	&& cd /opt && curl http://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-rtps/eprosima-fast-rtps-1-5-0/eprosima_fastrtps-1-5-0-linux-tar-gz?format=raw | tar xz eProsima_FastRTPS-1.5.0-Linux/share/fastrtps/fastrtpsgen.jar eProsima_FastRTPS-1.5.0-Linux/bin/fastrtpsgen \
	&& ln -s /opt/eProsima_FastRTPS-1.5.0-Linux/bin/fastrtpsgen /usr/local/bin/fastrtpsgen \
	&& mkdir -p /usr/local/share/fastrtps && ln -s /opt/eProsima_FastRTPS-1.5.0-Linux/share/fastrtps/fastrtpsgen.jar /usr/local/share/fastrtps/fastrtpsgen.jar \
	# cleanup
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

ENV CCACHE_MAXSIZE=1G
ENV PATH "/usr/lib/ccache:$PATH"
ENV TERM=xterm

# SITL UDP PORTS
EXPOSE 14556/udp
EXPOSE 14557/udp

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
