#
# PX4 ROS development environment
#

FROM px4io/px4-dev-base:latest
MAINTAINER Daniel Agar <daniel@agar.ca>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116 \
	&& sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list' \
	&& sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu/ xenial main" > /etc/apt/sources.list.d/ros-shadow.list' \
	&& apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		geographiclib-tools \
		libeigen3-dev \
		libgeographic-dev \
		libopencv-dev \
		protobuf-compiler \
		python-catkin-tools \
		python-tk \
		ros-melodic-gazebo-ros-pkgs \
		ros-melodic-mavlink \
		ros-melodic-mavros \
		ros-melodic-mavros-extras \
		ros-melodic-pcl-conversions \
		ros-melodic-pcl-msgs \
		ros-melodic-pcl-ros \
		ros-melodic-ros-base \
		ros-melodic-rostest \
		ros-melodic-rosunit \
	&& geographiclib-get-geoids egm96-5 \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	# pip
	&& pip install --upgrade matplotlib numpy px4tools pymavlink \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN rosdep init && rosdep update
