#
# PX4 development environment based on Arch Linux
#

FROM archlinux/base:latest
LABEL maintainer="Julien Lecoeur <julien.lecoeur@gmail.com>"

RUN	pacman -Sy --noconfirm \
		arm-none-eabi-gcc \
		arm-none-eabi-newlib \
		base-devel \
		ccache \
		cmake \
		git \
		gnutls \
		jdk11-openjdk \
		make \
		nettle \
		ninja \
		python-pip \
		tar \
		unzip \
		vim \
		wget \
		zip

# Install python dependencies
RUN	pip install \
		cerberus \
		empy \
		jinja2 \
		numpy \
		pyyaml \
		serial \
		toml

# Install genromfs
RUN	wget https://sourceforge.net/projects/romfs/files/genromfs/0.5.2/genromfs-0.5.2.tar.gz \
	&& tar zxvf genromfs-0.5.2.tar.gz \
	&& cd genromfs-0.5.2 && make && make install && cd .. \
	&& rm genromfs-0.5.2.tar.gz genromfs-0.5.2 -r

# Install gosu
RUN	curl -sSL https://github.com/tianon/gosu/releases/download/1.8/gosu-amd64 > /usr/sbin/gosu \
	&& chmod +x /usr/sbin/gosu

# Gradle (Required to build Fast-RTPS)
RUN wget -q "https://services.gradle.org/distributions/gradle-5.4.1-bin.zip" -O /tmp/gradle-5.4.1-bin.zip \
	&& mkdir /opt/gradle \
	&& cd /tmp \
	&& unzip -d /opt/gradle gradle-5.4.1-bin.zip \
	&& rm -rf /tmp/*

ENV PATH "/opt/gradle/gradle-5.4.1/bin:$PATH"

# Fast-RTPS
RUN wget -q "http://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-rtps/eprosima-fast-rtps-1-8-1/eprosima_fastrtps-1-8-1-linux-tar-gz?format=raw" -O /tmp/eprosima_fastrtps.tar.gz \
	&& cd /tmp && tar zxf eprosima_fastrtps.tar.gz \
	&& cd eProsima_FastRTPS-1.8.1-Linux \
	&& cd requiredcomponents \
	&& tar -xvzf eProsima_Fast-CDR-1.0.10-Linux.tar.gz \
	&& cd Fast-CDR-1.0.10 \
	&& mkdir build && cd build \
	&& cmake .. && cmake --build . --target install \
	&& cd ../../.. && cd eProsima_FastRTPS-1.8.1-Linux \
	&& mkdir build && cd build \
	&& cmake -DSECURITY=ON .. \
	&& cmake --build . --target install \
	&& rm -rf /tmp/*

# Fast-RTPS-Gen (required since Fast-RTPS-Gen got split from Fast-RTPS repo since 1.8.x)
RUN git clone https://github.com/eProsima/Fast-RTPS-Gen.git /tmp/Fast-RTPS-Gen \
	&& cd /tmp/Fast-RTPS-Gen \
	&& gradle assemble \
	&& cp share/fastrtps/fastrtpsgen.jar /usr/local/share/fastrtps/ \
	&& cp scripts/fastrtpsgen /usr/local/bin/ \
	&& rm -rf /tmp/*

# Add group dialout
RUN	groupadd dialout

# manual ccache setup
RUN	ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-gcc \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-g++

ENV CCACHE_MAXSIZE=1G
ENV FASTRTPSGEN_DIR="/usr/local/bin/"
ENV PATH "/usr/lib/ccache/bin:$PATH"
ENV TERM=xterm

# SITL UDP PORTS
EXPOSE 14556/udp
EXPOSE 14557/udp

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
