#
# PX4 gazebo development environment
#

FROM px4io/px4-dev-nuttx
MAINTAINER Daniel Agar <daniel@agar.ca>

RUN wget --quiet http://packages.osrfoundation.org/gazebo.key -O - | apt-key add - \
	&& sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list' \
	&& apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		ant \
		gazebo7 \
		gstreamer1.0-plugins-base \
		libeigen3-dev \
		libgazebo7-dev \
		libopencv-dev \
		openjdk-8-jdk \
		protobuf-compiler \
		python-dev \
		python-numpy \
		python-pip \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	# px4tools, pymavlink
	&& pip install --upgrade pip \
	&& pip install setuptools \
	&& pip install px4tools pymavlink \
	# dronekit
	&& git clone https://github.com/dronekit/dronekit-python.git \
	&& cd dronekit-python && pip install -r requirements.txt \
	&& cd .. && rm -rf dronekit-python \
	# cleanup
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Some QT-Apps/Gazebo don't not show controls without this
ENV QT_X11_NO_MITSHM 1
