#
# PX4 development environment based on Arch Linux
#

FROM archlinux/base:latest
MAINTAINER Julien Lecoeur <julien.lecoeur@gmail.com>

RUN	pacman -Sy --noconfirm \
		arm-none-eabi-gcc \
		arm-none-eabi-newlib \
		base-devel \
		ccache \
		cmake \
		git \
		make \
		ninja \
		python-pip \
		tar \
		unzip \
		vim \
		wget \
		zip

# Install python dependencies
RUN	pip install \
		cerberus \
		empy \
		jinja2 \
		numpy \
		pyyaml \
		serial \
		toml

# Install genromfs
RUN	wget https://sourceforge.net/projects/romfs/files/genromfs/0.5.2/genromfs-0.5.2.tar.gz \
	&& tar zxvf genromfs-0.5.2.tar.gz \
	&& cd genromfs-0.5.2 && make && make install && cd .. \
	&& rm genromfs-0.5.2.tar.gz genromfs-0.5.2 -r

# Install gosu
RUN	curl -sSL https://github.com/tianon/gosu/releases/download/1.8/gosu-amd64 > /usr/sbin/gosu \
	&& chmod +x /usr/sbin/gosu

# Add group dialout
RUN	groupadd dialout

# manual ccache setup
RUN	ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-gcc \
	&& ln -s /usr/bin/ccache /usr/lib/ccache/bin/arm-none-eabi-g++

ENV CCACHE_MAXSIZE=1G
ENV PATH "/usr/lib/ccache/bin:$PATH"
ENV TERM=xterm

# SITL UDP PORTS
EXPOSE 14556/udp
EXPOSE 14557/udp

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
