#
# PX4 NuttX development environment jenkins slave
#

FROM px4io/px4-dev-nuttx
MAINTAINER Daniel Agar <daniel@agar.ca>

ARG VERSION=3.14
ARG AGENT_WORKDIR=/home/jenkins/agent

ENV HOME /home/jenkins

RUN groupadd -g 10000 jenkins \
	&& useradd -c "Jenkins user" -d $HOME -u 10000 -g 10000 -m jenkins \
	&& apt-get install -yy openjdk-8-jre-headless \
	&&curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar \
	&& chmod 755 /usr/share/jenkins \
	&& chmod 644 /usr/share/jenkins/slave.jar

USER jenkins
ENV AGENT_WORKDIR=${AGENT_WORKDIR}
RUN mkdir /home/jenkins/.jenkins && mkdir -p ${AGENT_WORKDIR}

VOLUME /home/jenkins/.jenkins
VOLUME ${AGENT_WORKDIR}
WORKDIR /home/jenkins

COPY scripts/jenkins-slave /usr/local/bin/jenkins-slave

ENTRYPOINT ["jenkins-slave"]
